name: Build and Trivy Scan

on:
  push:
  pull_request:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  build-and-scan:
    name: Build container and scan with Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: |
          docker build -t local/trivy-scanner-test:${{ github.sha }} .

      - name: Trivy scan (audit mode - show all vulnerabilities)
        uses: aquasecurity/trivy-action@0.33.0
        with:
          scan-type: 'image'
          image-ref: local/trivy-scanner-test:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'

      - name: Trivy scan (SARIF)
        if: always()
        uses: aquasecurity/trivy-action@0.33.0
        with:
          scan-type: 'image'
          image-ref: local/trivy-scanner-test:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'

      - name: Trivy scan (JSON)
        if: always()
        uses: aquasecurity/trivy-action@0.33.0
        with:
          scan-type: 'image'
          image-ref: local/trivy-scanner-test:${{ github.sha }}
          format: 'json'
          output: 'trivy-results.json'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'

      - name: Trivy scan (CSV - using template)
        if: always()
        run: |
          trivy image \
            --format template \
            --template "@contrib/csv.tpl" \
            --output trivy-results.csv \
            --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL \
            --vuln-type os,library \
            local/trivy-scanner-test:${{ github.sha }}

      - name: Upload Trivy reports as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: |
            trivy-results.sarif
            trivy-results.json
            trivy-results.csv
          retention-days: 30

      - name: Upload SARIF to code scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

