name: Build and Trivy Scan

on:
  push:
  pull_request:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  build-and-scan:
    name: Build container and scan with Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: |
          docker build -t local/trivy-scanner-test:${{ github.sha }} .

      - name: Trivy scan (fail on HIGH/CRITICAL)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: local/trivy-scanner-test:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Trivy scan (SARIF)
        if: always()
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: local/trivy-scanner-test:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          ignore-unfixed: false
          vuln-type: 'os,library'

      - name: Upload SARIF to code scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

